version: '3.4'

services:
  s_apigateway:
    container_name: c_apigateway
    image: zormax/apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    networks:
      - net_api
      - int_net_api
    ports:
      - 80:80

  s_contact_api:
    container_name: c_contact_api
    image: zormax/contactapi
    build:
      context: .
      dockerfile: Services/Contact/Contact.API/Dockerfile
    networks:
      - int_net_api
    ports:
      - 7000:7000

  s_res_api:
    container_name: c_res_api
    image: zormax/resapi
    build:
      context: .
      dockerfile: Services/Reservation/Reservation.API/Dockerfile
    networks:
      - int_net_api
    ports:
      - 7001:7001


networks:
  net_api:
    driver: bridge

  int_net_api:
    internal: true
